// generate-flags-index.js

import { mkdir, readdir, writeFile } from 'fs';
import { join, parse } from 'path';
import { fileURLToPath } from 'url';
import * as path from 'path';
import sharp from 'sharp';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const FLAGS_DIR = path.resolve(__dirname, '../flags');
const FLAGS_DIR_RELATIVE_TO_SCRIPT = '../../assets/flags';
const INDEX_FILE_PATH = join(__dirname, 'flags.js');
const generateIndexFile = () => {
    const flagsDirPath = path.resolve(__dirname, FLAGS_DIR_RELATIVE_TO_SCRIPT);

    mkdir(FLAGS_DIR, { recursive: true }, (mkdirerr) => {
        if (mkdirerr) {
            console.error('Error reading flags directory:', mkdirerr);
            return;
        }

        readdir(flagsDirPath, async (rerr, files) => {
            if (rerr) {
                console.error('Error reading flags directory:', rerr);
                return;
            }

            const promises = files
                .filter(file => (file.endsWith('.svg') || file.endsWith('.png') || file.endsWith('.jpg')) && parse(file).name.length === 3)
                .map(async file => {
                    const svgFilePath = path.join(flagsDirPath, file);
                    const pngFileName = path.parse(file).name + '.png';
                    const pngFilePath = path.join(FLAGS_DIR, pngFileName);
                    await sharp(svgFilePath).png().toFile(pngFilePath);

                    const requirePath = `../flags/${pngFileName}`;
                    const iconPath = `/flags/${file}`;
                    return `  '${iconPath}': require('${requirePath}'),`;
                });

            const flagEntries = await Promise.all(promises);

            const fileContent = [
                '// This file is auto-generated by generate-flags-index.js. Do not edit manually.',
                'const flags = {',
                ...flagEntries,
                '};',
                '',
                'export default flags;',
            ].join('\n');

            writeFile(INDEX_FILE_PATH, fileContent, (werr) => {
                if (werr) {
                    console.error('Error writing index.js file:', werr);
                    return;
                }
                console.log(`Successfully generated ${INDEX_FILE_PATH}`);
                console.log('Total flags found:', flagEntries.length);
            });
        });
    });
};

generateIndexFile();
