export const Countries = [
  { name: 'Afghanistan', ioc: 'AFG' },
  { name: 'Albania', ioc: 'ALB' },
  { name: 'Algeria', ioc: 'ALG' },
  { name: 'Andorra', ioc: 'AND' },
  { name: 'Angola', ioc: 'ANG' },
  { name: 'Antigua and Barbuda', ioc: 'ANT' },
  { name: 'Argentina', ioc: 'ARG' },
  { name: 'Armenia', ioc: 'ARM' },
  { name: 'Aruba', ioc: 'ARU' },
  { name: 'American Samoa', ioc: 'ASA' },
  { name: 'Australia', ioc: 'AUS' },
  { name: 'Austria', ioc: 'AUT' },
  { name: 'Azerbaijan', ioc: 'AZE' },
  { name: 'Bahamas', ioc: 'BAH' },
  { name: 'Bangladesh', ioc: 'BAN' },
  { name: 'Barbados', ioc: 'BAR' },
  { name: 'Burundi', ioc: 'BDI' },
  { name: 'Belgium', ioc: 'BEL' },
  { name: 'Benin', ioc: 'BEN' },
  { name: 'Bermuda', ioc: 'BER' },
  { name: 'Bhutan', ioc: 'BHU' },
  { name: 'Bosnia and Herzegovina', ioc: 'BIH' },
  { name: 'Belize', ioc: 'BIZ' },
  { name: 'Belarus', ioc: 'BLR' },
  { name: 'Bolivia', ioc: 'BOL' },
  { name: 'Botswana', ioc: 'BOT' },
  { name: 'Brazil', ioc: 'BRA' },
  { name: 'Bahrain', ioc: 'BRN' },
  { name: 'Brunei', ioc: 'BRU' },
  { name: 'Bulgaria', ioc: 'BUL' },
  { name: 'Burkina Faso', ioc: 'BUR' },
  { name: 'Central African Republic', ioc: 'CAF' },
  { name: 'Cambodia', ioc: 'CAM' },
  { name: 'Canada', ioc: 'CAN' },
  { name: 'Cayman Islands', ioc: 'CAY' },
  { name: 'Republic of the Congo', ioc: 'CGO' },
  { name: 'Chad', ioc: 'CHA' },
  { name: 'Chile', ioc: 'CHI' },
  { name: "People's Republic of China", ioc: 'CHN' },
  { name: 'Ivory Coast', ioc: 'CIV' },
  { name: 'Cameroon', ioc: 'CMR' },
  { name: 'Democratic Republic of the Congo', ioc: 'COD' },
  { name: 'Cook Islands', ioc: 'COK' },
  { name: 'Colombia', ioc: 'COL' },
  { name: 'Comoros', ioc: 'COM' },
  { name: 'Cape Verde', ioc: 'CPV' },
  { name: 'Costa Rica', ioc: 'CRC' },
  { name: 'Croatia', ioc: 'CRO' },
  { name: 'Cuba', ioc: 'CUB' },
  { name: 'Cyprus', ioc: 'CYP' },
  { name: 'Czech Republic Czechia', ioc: 'CZE' },
  { name: 'Denmark', ioc: 'DEN' },
  { name: 'Djibouti', ioc: 'DJI' },
  { name: 'Dominica', ioc: 'DMA' },
  { name: 'Dominican Republic', ioc: 'DOM' },
  { name: 'Ecuador', ioc: 'ECU' },
  { name: 'Egypt', ioc: 'EGY' },
  { name: 'Eritrea', ioc: 'ERI' },
  { name: 'El Salvador', ioc: 'ESA' },
  { name: 'Spain', ioc: 'ESP' },
  { name: 'Estonia', ioc: 'EST' },
  { name: 'Ethiopia', ioc: 'ETH' },
  { name: 'Fiji', ioc: 'FIJ' },
  { name: 'Finland', ioc: 'FIN' },
  { name: 'France', ioc: 'FRA' },
  { name: 'Federated States of Micronesia', ioc: 'FSM' },
  { name: 'Gabon', ioc: 'GAB' },
  { name: 'The Gambia', ioc: 'GAM' },
  { name: 'Great Britain', ioc: 'GBR' },
  { name: 'Guinea-Bissau', ioc: 'GBS' },
  { name: 'Georgia', ioc: 'GEO' },
  { name: 'Equatorial Guinea', ioc: 'GEQ' },
  { name: 'Germany', ioc: 'GER' },
  { name: 'Ghana', ioc: 'GHA' },
  { name: 'Greece', ioc: 'GRE' },
  { name: 'Grenada', ioc: 'GRN' },
  { name: 'Guatemala', ioc: 'GUA' },
  { name: 'Guinea', ioc: 'GUI' },
  { name: 'Guam', ioc: 'GUM' },
  { name: 'Guyana', ioc: 'GUY' },
  { name: 'Haiti', ioc: 'HAI' },
  { name: 'Hong Kong', ioc: 'HKG' },
  { name: 'Honduras', ioc: 'HON' },
  { name: 'Hungary', ioc: 'HUN' },
  { name: 'Indonesia', ioc: 'INA' },
  { name: 'India', ioc: 'IND' },
  { name: 'Iran', ioc: 'IRI' },
  { name: 'Ireland', ioc: 'IRL' },
  { name: 'Iraq', ioc: 'IRQ' },
  { name: 'Iceland', ioc: 'ISL' },
  { name: 'Israel', ioc: 'ISR' },
  { name: 'Virgin Islands', ioc: 'ISV' },
  { name: 'Italy', ioc: 'ITA' },
  { name: 'British Virgin Islands', ioc: 'IVB' },
  { name: 'Jamaica', ioc: 'JAM' },
  { name: 'Jordan', ioc: 'JOR' },
  { name: 'Japan', ioc: 'JPN' },
  { name: 'Kazakhstan', ioc: 'KAZ' },
  { name: 'Kenya', ioc: 'KEN' },
  { name: 'Kyrgyzstan', ioc: 'KGZ' },
  { name: 'Kiribati', ioc: 'KIR' },
  { name: 'South Korea', ioc: 'KOR' },
  { name: 'Kosovo', ioc: 'KOS' },
  { name: 'Saudi Arabia', ioc: 'KSA' },
  { name: 'Kuwait', ioc: 'KUW' },
  { name: 'Laos', ioc: 'LAO' },
  { name: 'Latvia', ioc: 'LAT' },
  { name: 'Libya', ioc: 'LBA' },
  { name: 'Lebanon', ioc: 'LBN' },
  { name: 'Liberia', ioc: 'LBR' },
  { name: 'Saint Lucia', ioc: 'LCA' },
  { name: 'Lesotho', ioc: 'LES' },
  { name: 'Liechtenstein', ioc: 'LIE' },
  { name: 'Lithuania', ioc: 'LTU' },
  { name: 'Luxembourg', ioc: 'LUX' },
  { name: 'Madagascar', ioc: 'MAD' },
  { name: 'Morocco', ioc: 'MAR' },
  { name: 'Malaysia', ioc: 'MAS' },
  { name: 'Malawi', ioc: 'MAW' },
  { name: 'Moldova', ioc: 'MDA' },
  { name: 'Maldives', ioc: 'MDV' },
  { name: 'Mexico', ioc: 'MEX' },
  { name: 'Mongolia', ioc: 'MGL' },
  { name: 'Marshall Islands', ioc: 'MHL' },
  { name: 'North Macedonia', ioc: 'MKD' },
  { name: 'Mali', ioc: 'MLI' },
  { name: 'Malta', ioc: 'MLT' },
  { name: 'Montenegro', ioc: 'MNE' },
  { name: 'Monaco', ioc: 'MON' },
  { name: 'Mozambique', ioc: 'MOZ' },
  { name: 'Mauritius', ioc: 'MRI' },
  { name: 'Mauritania', ioc: 'MTN' },
  { name: 'Myanmar', ioc: 'MYA' },
  { name: 'Namibia', ioc: 'NAM' },
  { name: 'Nicaragua', ioc: 'NCA' },
  { name: 'Netherlands', ioc: 'NED' },
  { name: 'Nepal', ioc: 'NEP' },
  { name: 'Nigeria', ioc: 'NGR' },
  { name: 'Niger', ioc: 'NIG' },
  { name: 'Norway', ioc: 'NOR' },
  { name: 'Nauru', ioc: 'NRU' },
  { name: 'New Zealand', ioc: 'NZL' },
  { name: 'Oman', ioc: 'OMA' },
  { name: 'Pakistan', ioc: 'PAK' },
  { name: 'Panama', ioc: 'PAN' },
  { name: 'Paraguay', ioc: 'PAR' },
  { name: 'Peru', ioc: 'PER' },
  { name: 'Philippines', ioc: 'PHI' },
  { name: 'Palestine', ioc: 'PLE' },
  { name: 'Palau', ioc: 'PLW' },
  { name: 'Papua New Guinea', ioc: 'PNG' },
  { name: 'Poland', ioc: 'POL' },
  { name: 'Portugal', ioc: 'POR' },
  { name: 'North Korea', ioc: 'PRK' },
  { name: 'Puerto Rico', ioc: 'PUR' },
  { name: 'Qatar', ioc: 'QAT' },
  { name: 'Romania', ioc: 'ROU' },
  { name: 'South Africa', ioc: 'RSA' },
  { name: 'Russia', ioc: 'RUS' },
  { name: 'Rwanda', ioc: 'RWA' },
  { name: 'Samoa', ioc: 'SAM' },
  { name: 'Senegal', ioc: 'SEN' },
  { name: 'Seychelles', ioc: 'SEY' },
  { name: 'Singapore', ioc: 'SGP' },
  { name: 'Saint Kitts and Nevis', ioc: 'SKN' },
  { name: 'Sierra Leone', ioc: 'SLE' },
  { name: 'Slovenia', ioc: 'SLO' },
  { name: 'San Marino', ioc: 'SMR' },
  { name: 'Solomon Islands', ioc: 'SOL' },
  { name: 'Somalia', ioc: 'SOM' },
  { name: 'Serbia', ioc: 'SRB' },
  { name: 'Sri Lanka', ioc: 'SRI' },
  { name: 'South Sudan', ioc: 'SSD' },
  { name: 'São Tomé and Príncipe', ioc: 'STP' },
  { name: 'Sudan', ioc: 'SUD' },
  { name: 'Switzerland', ioc: 'SUI' },
  { name: 'Suriname', ioc: 'SUR' },
  { name: 'Slovakia', ioc: 'SVK' },
  { name: 'Sweden', ioc: 'SWE' },
  { name: 'Eswatini Eswatini', ioc: 'SWZ' },
  { name: 'Syria', ioc: 'SYR' },
  { name: 'Tanzania', ioc: 'TAN' },
  { name: 'Tonga', ioc: 'TGA' },
  { name: 'Thailand', ioc: 'THA' },
  { name: 'Tajikistan', ioc: 'TJK' },
  { name: 'Turkmenistan', ioc: 'TKM' },
  { name: 'Timor-Leste', ioc: 'TLS' },
  { name: 'Togo', ioc: 'TOG' },
  { name: 'Republic of China', ioc: 'TPE' },
  { name: 'Trinidad and Tobago', ioc: 'TTO' },
  { name: 'Tunisia', ioc: 'TUN' },
  { name: 'Turkey', ioc: 'TUR' },
  { name: 'Tuvalu', ioc: 'TUV' },
  { name: 'United Arab Emirates', ioc: 'UAE' },
  { name: 'Uganda', ioc: 'UGA' },
  { name: 'Ukraine', ioc: 'UKR' },
  { name: 'Uruguay', ioc: 'URU' },
  { name: 'United States', ioc: 'USA' },
  { name: 'Uzbekistan', ioc: 'UZB' },
  { name: 'Vanuatu', ioc: 'VAN' },
  { name: 'Venezuela', ioc: 'VEN' },
  { name: 'Vietnam', ioc: 'VIE' },
  { name: 'Saint Vincent and the Grenadines', ioc: 'VIN' },
  { name: 'Yemen', ioc: 'YEM' },
  { name: 'Zambia', ioc: 'ZAM' },
  { name: 'Zimbabwe', ioc: 'ZIM' },
];
