#!/bin/sh

npm run sync || ( echo 'Please review and add changed files to git staging area' 1>&2 && exit 1 )

if [ ! -f '.xandroid' ]
then
	npm run version:android:increment
	echo 'Please review and add changed files to the git staging area' 1>&2
	exit 1
else
	echo 'Removing .xandroid file' 1>&2
	rm -f .xandroid
fi
